title: GO-EUREKA Network
name: GO-EUREKA Network
description: Research network focused on tsunami early warning using ionospheric signals.
url: "https://iono-eureka.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty
exclude:
  - Dylan-notes.txt

collections:
  events:
    output: true
    permalink: /events/:name/
  news:
    output: true
    permalink: /news/:name/

defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: post
      section: events
  - scope:
      path: ""
      type: news
    values:
      layout: post
      section: news
